[package]
name = "muncher"
version = "0.1.0"
authors = ["Casey Waldren <caseywaldren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
clap = "~2.31.2"
humantime = "~1.2.0"
